# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ClientConfigurationResponse(BaseModel):
    """
    Represents a versioned client configuration record.  # noqa: E501
    """
    name:  StrictStr = Field(...,alias="name", description="The logical name of the configuration.") 
    config_type:  StrictStr = Field(...,alias="configType", description="The category of configuration.") 
    major_version: StrictInt = Field(description="The major version number.", alias="majorVersion")
    minor_version: StrictInt = Field(description="The minor version number.", alias="minorVersion")
    value:  StrictStr = Field(...,alias="value", description="The JSON configuration value.") 
    is_draft: StrictBool = Field(description="Whether this version is still in draft state. Draft versions can be edited; locked versions cannot.", alias="isDraft")
    __properties = ["name", "configType", "majorVersion", "minorVersion", "value", "isDraft"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClientConfigurationResponse:
        """Create an instance of ClientConfigurationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClientConfigurationResponse:
        """Create an instance of ClientConfigurationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClientConfigurationResponse.parse_obj(obj)

        _obj = ClientConfigurationResponse.parse_obj({
            "name": obj.get("name"),
            "config_type": obj.get("configType"),
            "major_version": obj.get("majorVersion"),
            "minor_version": obj.get("minorVersion"),
            "value": obj.get("value"),
            "is_draft": obj.get("isDraft")
        })
        return _obj

ClientConfigurationResponse.update_forward_refs()
