# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class CreateVersionedConfigurationDraftRequest(BaseModel):
    """
    Request to create a new draft versioned configuration.  # noqa: E501
    """
    major_version: Optional[StrictInt] = Field(default=None, description="The major version for the new draft. Must be supplied together with minorVersion, or both omitted to auto-assign the next version.", alias="majorVersion")
    minor_version: Optional[StrictInt] = Field(default=None, description="The minor version for the new draft. Must be supplied together with MajorVersion, or both omitted to auto-assign the next version.", alias="minorVersion")
    source_major_version: Optional[StrictInt] = Field(default=None, description="The major version of an existing record to copy the value from. Must be supplied together with SourceMinorVersion. If omitted, the new draft is initialised with an empty JSON object.", alias="sourceMajorVersion")
    source_minor_version: Optional[StrictInt] = Field(default=None, description="The minor version of an existing record to copy the value from. Must be supplied together with SourceMajorVersion. If omitted, the new draft is initialised with an empty JSON object.", alias="sourceMinorVersion")
    __properties = ["majorVersion", "minorVersion", "sourceMajorVersion", "sourceMinorVersion"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateVersionedConfigurationDraftRequest:
        """Create an instance of CreateVersionedConfigurationDraftRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if major_version (nullable) is None
        # and __fields_set__ contains the field
        if self.major_version is None and "major_version" in self.__fields_set__:
            _dict['majorVersion'] = None

        # set to None if minor_version (nullable) is None
        # and __fields_set__ contains the field
        if self.minor_version is None and "minor_version" in self.__fields_set__:
            _dict['minorVersion'] = None

        # set to None if source_major_version (nullable) is None
        # and __fields_set__ contains the field
        if self.source_major_version is None and "source_major_version" in self.__fields_set__:
            _dict['sourceMajorVersion'] = None

        # set to None if source_minor_version (nullable) is None
        # and __fields_set__ contains the field
        if self.source_minor_version is None and "source_minor_version" in self.__fields_set__:
            _dict['sourceMinorVersion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateVersionedConfigurationDraftRequest:
        """Create an instance of CreateVersionedConfigurationDraftRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateVersionedConfigurationDraftRequest.parse_obj(obj)

        _obj = CreateVersionedConfigurationDraftRequest.parse_obj({
            "major_version": obj.get("majorVersion"),
            "minor_version": obj.get("minorVersion"),
            "source_major_version": obj.get("sourceMajorVersion"),
            "source_minor_version": obj.get("sourceMinorVersion")
        })
        return _obj

CreateVersionedConfigurationDraftRequest.update_forward_refs()
