# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ExternalLogRecord(BaseModel):
    """
    Represents an external log record.  # noqa: E501
    """
    logid: StrictInt = Field(description="The unique log identifier.")
    parentlogid: Optional[StrictInt] = Field(default=None, description="The parent log identifier (null is allowed).")
    loglevel:  StrictStr = Field(...,alias="loglevel", description="The log level.") 
    logstatus:  StrictStr = Field(...,alias="logstatus", description="The log status.") 
    sourcerecordtype:  Optional[StrictStr] = Field(None,alias="sourcerecordtype", description="The source record type.") 
    sourceprimaryidtype:  Optional[StrictStr] = Field(None,alias="sourceprimaryidtype", description="The source primary ID type.") 
    sourceprimaryidvalue:  Optional[StrictStr] = Field(None,alias="sourceprimaryidvalue", description="The source primary ID value.") 
    targetrecordtype:  Optional[StrictStr] = Field(None,alias="targetrecordtype", description="The target record type.") 
    targetrecordaction:  Optional[StrictStr] = Field(None,alias="targetrecordaction", description="The target record action.") 
    targetprimaryidtype:  Optional[StrictStr] = Field(None,alias="targetprimaryidtype", description="The target primary ID type.") 
    targetprimaryidvalue:  Optional[StrictStr] = Field(None,alias="targetprimaryidvalue", description="The target primary ID value.") 
    message:  Optional[StrictStr] = Field(None,alias="message", description="The log message.") 
    messagetype:  Optional[StrictStr] = Field(None,alias="messagetype", description="The message type.") 
    timestamp:  StrictStr = Field(...,alias="timestamp", description="The timestamp of the log record.") 
    __properties = ["logid", "parentlogid", "loglevel", "logstatus", "sourcerecordtype", "sourceprimaryidtype", "sourceprimaryidvalue", "targetrecordtype", "targetrecordaction", "targetprimaryidtype", "targetprimaryidvalue", "message", "messagetype", "timestamp"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExternalLogRecord:
        """Create an instance of ExternalLogRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if parentlogid (nullable) is None
        # and __fields_set__ contains the field
        if self.parentlogid is None and "parentlogid" in self.__fields_set__:
            _dict['parentlogid'] = None

        # set to None if sourcerecordtype (nullable) is None
        # and __fields_set__ contains the field
        if self.sourcerecordtype is None and "sourcerecordtype" in self.__fields_set__:
            _dict['sourcerecordtype'] = None

        # set to None if sourceprimaryidtype (nullable) is None
        # and __fields_set__ contains the field
        if self.sourceprimaryidtype is None and "sourceprimaryidtype" in self.__fields_set__:
            _dict['sourceprimaryidtype'] = None

        # set to None if sourceprimaryidvalue (nullable) is None
        # and __fields_set__ contains the field
        if self.sourceprimaryidvalue is None and "sourceprimaryidvalue" in self.__fields_set__:
            _dict['sourceprimaryidvalue'] = None

        # set to None if targetrecordtype (nullable) is None
        # and __fields_set__ contains the field
        if self.targetrecordtype is None and "targetrecordtype" in self.__fields_set__:
            _dict['targetrecordtype'] = None

        # set to None if targetrecordaction (nullable) is None
        # and __fields_set__ contains the field
        if self.targetrecordaction is None and "targetrecordaction" in self.__fields_set__:
            _dict['targetrecordaction'] = None

        # set to None if targetprimaryidtype (nullable) is None
        # and __fields_set__ contains the field
        if self.targetprimaryidtype is None and "targetprimaryidtype" in self.__fields_set__:
            _dict['targetprimaryidtype'] = None

        # set to None if targetprimaryidvalue (nullable) is None
        # and __fields_set__ contains the field
        if self.targetprimaryidvalue is None and "targetprimaryidvalue" in self.__fields_set__:
            _dict['targetprimaryidvalue'] = None

        # set to None if message (nullable) is None
        # and __fields_set__ contains the field
        if self.message is None and "message" in self.__fields_set__:
            _dict['message'] = None

        # set to None if messagetype (nullable) is None
        # and __fields_set__ contains the field
        if self.messagetype is None and "messagetype" in self.__fields_set__:
            _dict['messagetype'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExternalLogRecord:
        """Create an instance of ExternalLogRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExternalLogRecord.parse_obj(obj)

        _obj = ExternalLogRecord.parse_obj({
            "logid": obj.get("logid"),
            "parentlogid": obj.get("parentlogid"),
            "loglevel": obj.get("loglevel"),
            "logstatus": obj.get("logstatus"),
            "sourcerecordtype": obj.get("sourcerecordtype"),
            "sourceprimaryidtype": obj.get("sourceprimaryidtype"),
            "sourceprimaryidvalue": obj.get("sourceprimaryidvalue"),
            "targetrecordtype": obj.get("targetrecordtype"),
            "targetrecordaction": obj.get("targetrecordaction"),
            "targetprimaryidtype": obj.get("targetprimaryidtype"),
            "targetprimaryidvalue": obj.get("targetprimaryidvalue"),
            "message": obj.get("message"),
            "messagetype": obj.get("messagetype"),
            "timestamp": obj.get("timestamp")
        })
        return _obj

ExternalLogRecord.update_forward_refs()
