# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class FailedDeliveryResponse(BaseModel):
    """
    A batch's failed deliveries returned by the list endpoint, aggregated to one row per batch. Finbourne.Horizon.Integrations.Web.Dto.Integrations.TradePublicationFramework.Response.FailedDeliveryResponse.FailedCount is the number of failed deliveries in the batch and Finbourne.Horizon.Integrations.Web.Dto.Integrations.TradePublicationFramework.Response.FailedDeliveryResponse.FailureReason is the comma-separated set of their failure reasons.  # noqa: E501
    """
    batch_reference_id:  StrictStr = Field(...,alias="batchReferenceId") 
    run_id:  StrictStr = Field(...,alias="runId") 
    run_start_time: datetime = Field(alias="runStartTime")
    failed_count: StrictInt = Field(alias="failedCount")
    failure_reason:  StrictStr = Field(...,alias="failureReason") 
    last_attempt_at: datetime = Field(alias="lastAttemptAt")
    attempt_count: StrictInt = Field(alias="attemptCount")
    resolved: StrictBool
    resolved_at: Optional[datetime] = Field(default=None, alias="resolvedAt")
    resolution_reason:  Optional[StrictStr] = Field(None,alias="resolutionReason") 
    __properties = ["batchReferenceId", "runId", "runStartTime", "failedCount", "failureReason", "lastAttemptAt", "attemptCount", "resolved", "resolvedAt", "resolutionReason"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FailedDeliveryResponse:
        """Create an instance of FailedDeliveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if resolved_at (nullable) is None
        # and __fields_set__ contains the field
        if self.resolved_at is None and "resolved_at" in self.__fields_set__:
            _dict['resolvedAt'] = None

        # set to None if resolution_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.resolution_reason is None and "resolution_reason" in self.__fields_set__:
            _dict['resolutionReason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FailedDeliveryResponse:
        """Create an instance of FailedDeliveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FailedDeliveryResponse.parse_obj(obj)

        _obj = FailedDeliveryResponse.parse_obj({
            "batch_reference_id": obj.get("batchReferenceId"),
            "run_id": obj.get("runId"),
            "run_start_time": obj.get("runStartTime"),
            "failed_count": obj.get("failedCount"),
            "failure_reason": obj.get("failureReason"),
            "last_attempt_at": obj.get("lastAttemptAt"),
            "attempt_count": obj.get("attemptCount"),
            "resolved": obj.get("resolved"),
            "resolved_at": obj.get("resolvedAt"),
            "resolution_reason": obj.get("resolutionReason")
        })
        return _obj

FailedDeliveryResponse.update_forward_refs()
