# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class FileDestinationResponse(BaseModel):
    """
    record containing details of a single file destination for a run.  # noqa: E501
    """
    type:  StrictStr = Field(...,alias="type") 
    path:  StrictStr = Field(...,alias="path") 
    status:  StrictStr = Field(...,alias="status") 
    error:  Optional[StrictStr] = Field(None,alias="error") 
    failure_reason:  Optional[StrictStr] = Field(None,alias="failureReason") 
    __properties = ["type", "path", "status", "error", "failureReason"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FileDestinationResponse:
        """Create an instance of FileDestinationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if error (nullable) is None
        # and __fields_set__ contains the field
        if self.error is None and "error" in self.__fields_set__:
            _dict['error'] = None

        # set to None if failure_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.failure_reason is None and "failure_reason" in self.__fields_set__:
            _dict['failureReason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FileDestinationResponse:
        """Create an instance of FileDestinationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FileDestinationResponse.parse_obj(obj)

        _obj = FileDestinationResponse.parse_obj({
            "type": obj.get("type"),
            "path": obj.get("path"),
            "status": obj.get("status"),
            "error": obj.get("error"),
            "failure_reason": obj.get("failureReason")
        })
        return _obj

FileDestinationResponse.update_forward_refs()
