# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.instance_destinations import InstanceDestinations
from finbourne_horizon.models.tpf_portfolio import TpfPortfolio

class InstanceResponse(BaseModel):
    """
    record containing details of a single instance.  # noqa: E501
    """
    id:  StrictStr = Field(...,alias="id") 
    name:  StrictStr = Field(...,alias="name") 
    enabled: StrictBool
    portfolios: List[TpfPortfolio]
    schedule:  Optional[StrictStr] = Field(None,alias="schedule") 
    schedule_timezone:  Optional[StrictStr] = Field(None,alias="scheduleTimezone") 
    last_run_at: Optional[datetime] = Field(default=None, alias="lastRunAt")
    last_run_status:  Optional[StrictStr] = Field(None,alias="lastRunStatus") 
    latest_runs_in24_hours:  Optional[StrictStr] = Field(None,alias="latestRunsIn24Hours") 
    destinations: List[InstanceDestinations]
    __properties = ["id", "name", "enabled", "portfolios", "schedule", "scheduleTimezone", "lastRunAt", "lastRunStatus", "latestRunsIn24Hours", "destinations"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InstanceResponse:
        """Create an instance of InstanceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in portfolios (list)
        _items = []
        if self.portfolios:
            for _item in self.portfolios:
                if _item:
                    _items.append(_item.to_dict())
            _dict['portfolios'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item in self.destinations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['destinations'] = _items
        # set to None if schedule (nullable) is None
        # and __fields_set__ contains the field
        if self.schedule is None and "schedule" in self.__fields_set__:
            _dict['schedule'] = None

        # set to None if schedule_timezone (nullable) is None
        # and __fields_set__ contains the field
        if self.schedule_timezone is None and "schedule_timezone" in self.__fields_set__:
            _dict['scheduleTimezone'] = None

        # set to None if last_run_at (nullable) is None
        # and __fields_set__ contains the field
        if self.last_run_at is None and "last_run_at" in self.__fields_set__:
            _dict['lastRunAt'] = None

        # set to None if last_run_status (nullable) is None
        # and __fields_set__ contains the field
        if self.last_run_status is None and "last_run_status" in self.__fields_set__:
            _dict['lastRunStatus'] = None

        # set to None if latest_runs_in24_hours (nullable) is None
        # and __fields_set__ contains the field
        if self.latest_runs_in24_hours is None and "latest_runs_in24_hours" in self.__fields_set__:
            _dict['latestRunsIn24Hours'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InstanceResponse:
        """Create an instance of InstanceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InstanceResponse.parse_obj(obj)

        _obj = InstanceResponse.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "enabled": obj.get("enabled"),
            "portfolios": [TpfPortfolio.from_dict(_item) for _item in obj.get("portfolios")] if obj.get("portfolios") is not None else None,
            "schedule": obj.get("schedule"),
            "schedule_timezone": obj.get("scheduleTimezone"),
            "last_run_at": obj.get("lastRunAt"),
            "last_run_status": obj.get("lastRunStatus"),
            "latest_runs_in24_hours": obj.get("latestRunsIn24Hours"),
            "destinations": [InstanceDestinations.from_dict(_item) for _item in obj.get("destinations")] if obj.get("destinations") is not None else None
        })
        return _obj

InstanceResponse.update_forward_refs()
