# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class InstanceRunResponse(BaseModel):
    """
    Response containing details of a single run for an instance.  # noqa: E501
    """
    run_id:  StrictStr = Field(...,alias="runId") 
    batch_reference_id:  StrictStr = Field(...,alias="batchReferenceId") 
    attempt: Optional[StrictInt] = None
    start_time: datetime = Field(alias="startTime")
    end_time: Optional[datetime] = Field(default=None, alias="endTime")
    duration:  Optional[StrictStr] = Field(None,alias="duration") 
    status:  StrictStr = Field(...,alias="status") 
    triggered_by:  Optional[StrictStr] = Field(None,alias="triggeredBy") 
    total: StrictInt
    sent_count: StrictInt = Field(alias="sentCount")
    skipped_count: StrictInt = Field(alias="skippedCount")
    failed_count: StrictInt = Field(alias="failedCount")
    failed_files: StrictInt = Field(alias="failedFiles")
    __properties = ["runId", "batchReferenceId", "attempt", "startTime", "endTime", "duration", "status", "triggeredBy", "total", "sentCount", "skippedCount", "failedCount", "failedFiles"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InstanceRunResponse:
        """Create an instance of InstanceRunResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if attempt (nullable) is None
        # and __fields_set__ contains the field
        if self.attempt is None and "attempt" in self.__fields_set__:
            _dict['attempt'] = None

        # set to None if end_time (nullable) is None
        # and __fields_set__ contains the field
        if self.end_time is None and "end_time" in self.__fields_set__:
            _dict['endTime'] = None

        # set to None if duration (nullable) is None
        # and __fields_set__ contains the field
        if self.duration is None and "duration" in self.__fields_set__:
            _dict['duration'] = None

        # set to None if triggered_by (nullable) is None
        # and __fields_set__ contains the field
        if self.triggered_by is None and "triggered_by" in self.__fields_set__:
            _dict['triggeredBy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InstanceRunResponse:
        """Create an instance of InstanceRunResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InstanceRunResponse.parse_obj(obj)

        _obj = InstanceRunResponse.parse_obj({
            "run_id": obj.get("runId"),
            "batch_reference_id": obj.get("batchReferenceId"),
            "attempt": obj.get("attempt"),
            "start_time": obj.get("startTime"),
            "end_time": obj.get("endTime"),
            "duration": obj.get("duration"),
            "status": obj.get("status"),
            "triggered_by": obj.get("triggeredBy"),
            "total": obj.get("total"),
            "sent_count": obj.get("sentCount"),
            "skipped_count": obj.get("skippedCount"),
            "failed_count": obj.get("failedCount"),
            "failed_files": obj.get("failedFiles")
        })
        return _obj

InstanceRunResponse.update_forward_refs()
