# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.run_status_count import RunStatusCount

class LatestRunsResponse(BaseModel):
    """
    record containing the 24-hour run summary grouped by external status.  # noqa: E501
    """
    total: StrictInt
    status_counts: List[RunStatusCount] = Field(alias="statusCounts")
    __properties = ["total", "statusCounts"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LatestRunsResponse:
        """Create an instance of LatestRunsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in status_counts (list)
        _items = []
        if self.status_counts:
            for _item in self.status_counts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['statusCounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LatestRunsResponse:
        """Create an instance of LatestRunsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LatestRunsResponse.parse_obj(obj)

        _obj = LatestRunsResponse.parse_obj({
            "total": obj.get("total"),
            "status_counts": [RunStatusCount.from_dict(_item) for _item in obj.get("statusCounts")] if obj.get("statusCounts") is not None else None
        })
        return _obj

LatestRunsResponse.update_forward_refs()
