# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class PostProcessTask(BaseModel):
    """
    PostProcessTask
    """
    action:  StrictStr = Field(...,alias="action") 
    target_instance:  Optional[StrictStr] = Field(None,alias="targetInstance") 
    trigger_on:  StrictStr = Field(...,alias="triggerOn") 
    parameters: Optional[Any] = None
    __properties = ["action", "targetInstance", "triggerOn", "parameters"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostProcessTask:
        """Create an instance of PostProcessTask from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if target_instance (nullable) is None
        # and __fields_set__ contains the field
        if self.target_instance is None and "target_instance" in self.__fields_set__:
            _dict['targetInstance'] = None

        # set to None if parameters (nullable) is None
        # and __fields_set__ contains the field
        if self.parameters is None and "parameters" in self.__fields_set__:
            _dict['parameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostProcessTask:
        """Create an instance of PostProcessTask from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostProcessTask.parse_obj(obj)

        _obj = PostProcessTask.parse_obj({
            "action": obj.get("action"),
            "target_instance": obj.get("targetInstance"),
            "trigger_on": obj.get("triggerOn"),
            "parameters": obj.get("parameters")
        })
        return _obj

PostProcessTask.update_forward_refs()
