# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.replay_options import ReplayOptions

class ReplayTransactionsRequest(BaseModel):
    """
    Request to replay one or more transactions through a TPF instance. The instance ID is specified in the route path.  # noqa: E501
    """
    transaction_ids: List[StrictStr] = Field(description="List of transaction IDs to replay.", alias="transactionIds")
    mode:  StrictStr = Field(...,alias="mode", description="Replay mode - DryRun (preview only) or Committed (real send).") 
    destinations: Optional[List[StrictStr]] = Field(default=None, description="Target destinations for Committed mode. Required for Committed, forbidden for DryRun. Valid values: Drive, Sftp, S3, Local")
    options: Optional[ReplayOptions] = None
    __properties = ["transactionIds", "mode", "destinations", "options"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReplayTransactionsRequest:
        """Create an instance of ReplayTransactionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # set to None if destinations (nullable) is None
        # and __fields_set__ contains the field
        if self.destinations is None and "destinations" in self.__fields_set__:
            _dict['destinations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReplayTransactionsRequest:
        """Create an instance of ReplayTransactionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ReplayTransactionsRequest.parse_obj(obj)

        _obj = ReplayTransactionsRequest.parse_obj({
            "transaction_ids": obj.get("transactionIds"),
            "mode": obj.get("mode"),
            "destinations": obj.get("destinations"),
            "options": ReplayOptions.from_dict(obj.get("options")) if obj.get("options") is not None else None
        })
        return _obj

ReplayTransactionsRequest.update_forward_refs()
