# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ResolveFailedDeliveryResponse(BaseModel):
    """
    Response from resolving the failed deliveries for a batch without retry. Resolution is batch-level, so Finbourne.Horizon.Integrations.Web.Dto.Integrations.TradePublicationFramework.Response.ResolveFailedDeliveryResponse.ResolvedCount is the number of failed deliveries marked resolved.  # noqa: E501
    """
    batch_reference_id:  StrictStr = Field(...,alias="batchReferenceId") 
    resolved_count: StrictInt = Field(alias="resolvedCount")
    resolved: StrictBool
    resolved_at: datetime = Field(alias="resolvedAt")
    resolution_reason:  StrictStr = Field(...,alias="resolutionReason") 
    message:  StrictStr = Field(...,alias="message") 
    __properties = ["batchReferenceId", "resolvedCount", "resolved", "resolvedAt", "resolutionReason", "message"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ResolveFailedDeliveryResponse:
        """Create an instance of ResolveFailedDeliveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ResolveFailedDeliveryResponse:
        """Create an instance of ResolveFailedDeliveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ResolveFailedDeliveryResponse.parse_obj(obj)

        _obj = ResolveFailedDeliveryResponse.parse_obj({
            "batch_reference_id": obj.get("batchReferenceId"),
            "resolved_count": obj.get("resolvedCount"),
            "resolved": obj.get("resolved"),
            "resolved_at": obj.get("resolvedAt"),
            "resolution_reason": obj.get("resolutionReason"),
            "message": obj.get("message")
        })
        return _obj

ResolveFailedDeliveryResponse.update_forward_refs()
