# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.file_destination_response import FileDestinationResponse

class RunFileResponse(BaseModel):
    """
    record containing details of a single file for a run.  # noqa: E501
    """
    file_name:  StrictStr = Field(...,alias="fileName") 
    generated_at: datetime = Field(alias="generatedAt")
    row_count: StrictInt = Field(alias="rowCount")
    file_hash:  StrictStr = Field(...,alias="fileHash") 
    encrypted: StrictBool
    destinations: List[FileDestinationResponse]
    transaction_ids: List[StrictStr] = Field(alias="transactionIds")
    __properties = ["fileName", "generatedAt", "rowCount", "fileHash", "encrypted", "destinations", "transactionIds"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RunFileResponse:
        """Create an instance of RunFileResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item in self.destinations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['destinations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RunFileResponse:
        """Create an instance of RunFileResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RunFileResponse.parse_obj(obj)

        _obj = RunFileResponse.parse_obj({
            "file_name": obj.get("fileName"),
            "generated_at": obj.get("generatedAt"),
            "row_count": obj.get("rowCount"),
            "file_hash": obj.get("fileHash"),
            "encrypted": obj.get("encrypted"),
            "destinations": [FileDestinationResponse.from_dict(_item) for _item in obj.get("destinations")] if obj.get("destinations") is not None else None,
            "transaction_ids": obj.get("transactionIds")
        })
        return _obj

RunFileResponse.update_forward_refs()
