# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.lusid_property_definition_overrides_by_type import LusidPropertyDefinitionOverridesByType

class SetInstanceOptionalPropertyMappingResponse(BaseModel):
    """
    Response for SetInstanceOptionalPropertyMapping.  # noqa: E501
    """
    property_overrides: Dict[str, LusidPropertyDefinitionOverridesByType] = Field(description="The full, current optional property mapping for the instance, after the write.", alias="propertyOverrides")
    warnings: List[StrictStr] = Field(description="Advisory warnings about a write that succeeded regardless, e.g. a future-dated effectiveFromOverride, or another enabled instance of the same integration holding a different effectiveFromOverride for the same property.")
    __properties = ["propertyOverrides", "warnings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SetInstanceOptionalPropertyMappingResponse:
        """Create an instance of SetInstanceOptionalPropertyMappingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each value in property_overrides (dict)
        _field_dict = {}
        if self.property_overrides:
            for _key in self.property_overrides:
                if self.property_overrides[_key]:
                    _field_dict[_key] = self.property_overrides[_key].to_dict()
            _dict['propertyOverrides'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SetInstanceOptionalPropertyMappingResponse:
        """Create an instance of SetInstanceOptionalPropertyMappingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SetInstanceOptionalPropertyMappingResponse.parse_obj(obj)

        _obj = SetInstanceOptionalPropertyMappingResponse.parse_obj({
            "property_overrides": dict(
                (_k, LusidPropertyDefinitionOverridesByType.from_dict(_v))
                for _k, _v in obj.get("propertyOverrides").items()
            )
            if obj.get("propertyOverrides") is not None
            else None,
            "warnings": obj.get("warnings")
        })
        return _obj

SetInstanceOptionalPropertyMappingResponse.update_forward_refs()
