# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.tpf_file_delivery_info import TpfFileDeliveryInfo

class TpfRetrySftpResponse(BaseModel):
    """
    Response from retrying SFTP file delivery  # noqa: E501
    """
    success: StrictBool = Field(description="Whether the retry was successful")
    message:  StrictStr = Field(...,alias="message", description="Status message describing the result") 
    new_file_delivery_id: Optional[StrictInt] = Field(default=None, description="ID of the new file delivery record created for this retry (if successful)", alias="newFileDeliveryId")
    retried_at: Optional[datetime] = Field(default=None, description="Timestamp when the retry was executed", alias="retriedAt")
    original_file: Optional[TpfFileDeliveryInfo] = Field(default=None, alias="originalFile")
    duplicate_file: Optional[TpfFileDeliveryInfo] = Field(default=None, alias="duplicateFile")
    __properties = ["success", "message", "newFileDeliveryId", "retriedAt", "originalFile", "duplicateFile"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TpfRetrySftpResponse:
        """Create an instance of TpfRetrySftpResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of original_file
        if self.original_file:
            _dict['originalFile'] = self.original_file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of duplicate_file
        if self.duplicate_file:
            _dict['duplicateFile'] = self.duplicate_file.to_dict()
        # set to None if new_file_delivery_id (nullable) is None
        # and __fields_set__ contains the field
        if self.new_file_delivery_id is None and "new_file_delivery_id" in self.__fields_set__:
            _dict['newFileDeliveryId'] = None

        # set to None if retried_at (nullable) is None
        # and __fields_set__ contains the field
        if self.retried_at is None and "retried_at" in self.__fields_set__:
            _dict['retriedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TpfRetrySftpResponse:
        """Create an instance of TpfRetrySftpResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TpfRetrySftpResponse.parse_obj(obj)

        _obj = TpfRetrySftpResponse.parse_obj({
            "success": obj.get("success"),
            "message": obj.get("message"),
            "new_file_delivery_id": obj.get("newFileDeliveryId"),
            "retried_at": obj.get("retriedAt"),
            "original_file": TpfFileDeliveryInfo.from_dict(obj.get("originalFile")) if obj.get("originalFile") is not None else None,
            "duplicate_file": TpfFileDeliveryInfo.from_dict(obj.get("duplicateFile")) if obj.get("duplicateFile") is not None else None
        })
        return _obj

TpfRetrySftpResponse.update_forward_refs()
