# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class TpfFileDeliveryResponse(BaseModel):
    """
    Response model for TPF file delivery search results  # noqa: E501
    """
    run_id:  Optional[StrictStr] = Field(None,alias="runId") 
    run_start_time: Optional[datetime] = Field(default=None, alias="runStartTime")
    file_name:  StrictStr = Field(...,alias="fileName") 
    generated_at: datetime = Field(alias="generatedAt")
    row_count: StrictInt = Field(alias="rowCount")
    file_hash:  Optional[StrictStr] = Field(None,alias="fileHash") 
    destination_type:  StrictStr = Field(...,alias="destinationType") 
    destination_path:  Optional[StrictStr] = Field(None,alias="destinationPath") 
    destination_status:  StrictStr = Field(...,alias="destinationStatus") 
    destination_error:  Optional[StrictStr] = Field(None,alias="destinationError") 
    destination_name:  Optional[StrictStr] = Field(None,alias="destinationName") 
    __properties = ["runId", "runStartTime", "fileName", "generatedAt", "rowCount", "fileHash", "destinationType", "destinationPath", "destinationStatus", "destinationError", "destinationName"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TpfFileDeliveryResponse:
        """Create an instance of TpfFileDeliveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if run_id (nullable) is None
        # and __fields_set__ contains the field
        if self.run_id is None and "run_id" in self.__fields_set__:
            _dict['runId'] = None

        # set to None if run_start_time (nullable) is None
        # and __fields_set__ contains the field
        if self.run_start_time is None and "run_start_time" in self.__fields_set__:
            _dict['runStartTime'] = None

        # set to None if file_hash (nullable) is None
        # and __fields_set__ contains the field
        if self.file_hash is None and "file_hash" in self.__fields_set__:
            _dict['fileHash'] = None

        # set to None if destination_path (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_path is None and "destination_path" in self.__fields_set__:
            _dict['destinationPath'] = None

        # set to None if destination_error (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_error is None and "destination_error" in self.__fields_set__:
            _dict['destinationError'] = None

        # set to None if destination_name (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_name is None and "destination_name" in self.__fields_set__:
            _dict['destinationName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TpfFileDeliveryResponse:
        """Create an instance of TpfFileDeliveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TpfFileDeliveryResponse.parse_obj(obj)

        _obj = TpfFileDeliveryResponse.parse_obj({
            "run_id": obj.get("runId"),
            "run_start_time": obj.get("runStartTime"),
            "file_name": obj.get("fileName"),
            "generated_at": obj.get("generatedAt"),
            "row_count": obj.get("rowCount"),
            "file_hash": obj.get("fileHash"),
            "destination_type": obj.get("destinationType"),
            "destination_path": obj.get("destinationPath"),
            "destination_status": obj.get("destinationStatus"),
            "destination_error": obj.get("destinationError"),
            "destination_name": obj.get("destinationName")
        })
        return _obj

TpfFileDeliveryResponse.update_forward_refs()
