# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class TpfTransactionSearchResponse(BaseModel):
    """
    TPF send history record  # noqa: E501
    """
    transaction_id:  StrictStr = Field(...,alias="transactionId", description="Transaction identifier") 
    instance_id:  StrictStr = Field(...,alias="instanceId", description="Integration instance ID where the transaction was processed") 
    instance_name:  StrictStr = Field(...,alias="instanceName", description="Integration instance name") 
    batch_id:  StrictStr = Field(...,alias="batchId", description="Unique identifier of the batch") 
    run_start_time: datetime = Field(description="Timestamp when the batch/run started", alias="runStartTime")
    publication_status:  StrictStr = Field(...,alias="publicationStatus", description="Publication status of the transaction (Sent | Skipped | Failed)") 
    instrument_name:  StrictStr = Field(...,alias="instrumentName", description="Instrument name") 
    instrument_type:  StrictStr = Field(...,alias="instrumentType", description="Instrument type") 
    trade_date: datetime = Field(description="Trade date of the transaction", alias="tradeDate")
    settlement_date: Optional[datetime] = Field(default=None, description="Settlement date of the transaction", alias="settlementDate")
    skip_reason:  Optional[StrictStr] = Field(None,alias="skipReason", description="Reason the transaction was skipped (if applicable)") 
    file_name:  Optional[StrictStr] = Field(None,alias="fileName", description="Output file associated with the publication run") 
    destinations: Optional[List[StrictStr]] = Field(default=None, description="Destinations to which the transaction was published")
    portfolio_code:  Optional[StrictStr] = Field(None,alias="portfolioCode", description="PortfolioCode showing portfolio code") 
    portfolio_scope:  Optional[StrictStr] = Field(None,alias="portfolioScope", description="PortfolioScope displaying portfolio scope") 
    failure_reason:  Optional[StrictStr] = Field(None,alias="failureReason", description="FailureReason to show failure reason") 
    instrument_id:  Optional[StrictStr] = Field(None,alias="instrumentId", description="InstrumentId showing instrument id of transaction") 
    __properties = ["transactionId", "instanceId", "instanceName", "batchId", "runStartTime", "publicationStatus", "instrumentName", "instrumentType", "tradeDate", "settlementDate", "skipReason", "fileName", "destinations", "portfolioCode", "portfolioScope", "failureReason", "instrumentId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TpfTransactionSearchResponse:
        """Create an instance of TpfTransactionSearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if settlement_date (nullable) is None
        # and __fields_set__ contains the field
        if self.settlement_date is None and "settlement_date" in self.__fields_set__:
            _dict['settlementDate'] = None

        # set to None if skip_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.skip_reason is None and "skip_reason" in self.__fields_set__:
            _dict['skipReason'] = None

        # set to None if file_name (nullable) is None
        # and __fields_set__ contains the field
        if self.file_name is None and "file_name" in self.__fields_set__:
            _dict['fileName'] = None

        # set to None if destinations (nullable) is None
        # and __fields_set__ contains the field
        if self.destinations is None and "destinations" in self.__fields_set__:
            _dict['destinations'] = None

        # set to None if portfolio_code (nullable) is None
        # and __fields_set__ contains the field
        if self.portfolio_code is None and "portfolio_code" in self.__fields_set__:
            _dict['portfolioCode'] = None

        # set to None if portfolio_scope (nullable) is None
        # and __fields_set__ contains the field
        if self.portfolio_scope is None and "portfolio_scope" in self.__fields_set__:
            _dict['portfolioScope'] = None

        # set to None if failure_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.failure_reason is None and "failure_reason" in self.__fields_set__:
            _dict['failureReason'] = None

        # set to None if instrument_id (nullable) is None
        # and __fields_set__ contains the field
        if self.instrument_id is None and "instrument_id" in self.__fields_set__:
            _dict['instrumentId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TpfTransactionSearchResponse:
        """Create an instance of TpfTransactionSearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TpfTransactionSearchResponse.parse_obj(obj)

        _obj = TpfTransactionSearchResponse.parse_obj({
            "transaction_id": obj.get("transactionId"),
            "instance_id": obj.get("instanceId"),
            "instance_name": obj.get("instanceName"),
            "batch_id": obj.get("batchId"),
            "run_start_time": obj.get("runStartTime"),
            "publication_status": obj.get("publicationStatus"),
            "instrument_name": obj.get("instrumentName"),
            "instrument_type": obj.get("instrumentType"),
            "trade_date": obj.get("tradeDate"),
            "settlement_date": obj.get("settlementDate"),
            "skip_reason": obj.get("skipReason"),
            "file_name": obj.get("fileName"),
            "destinations": obj.get("destinations"),
            "portfolio_code": obj.get("portfolioCode"),
            "portfolio_scope": obj.get("portfolioScope"),
            "failure_reason": obj.get("failureReason"),
            "instrument_id": obj.get("instrumentId")
        })
        return _obj

TpfTransactionSearchResponse.update_forward_refs()
