# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class TpfFileDeliveryInfo(BaseModel):
    """
    Information about a file delivery  # noqa: E501
    """
    id: StrictInt = Field(description="File delivery ID")
    file_name:  StrictStr = Field(...,alias="fileName", description="File name") 
    file_hash:  StrictStr = Field(...,alias="fileHash", description="SHA-256 hash of the file content") 
    destination_path:  StrictStr = Field(...,alias="destinationPath", description="SFTP destination path") 
    status:  StrictStr = Field(...,alias="status", description="Delivery status") 
    generated_at: datetime = Field(description="Timestamp when the file was originally generated", alias="generatedAt")
    __properties = ["id", "fileName", "fileHash", "destinationPath", "status", "generatedAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TpfFileDeliveryInfo:
        """Create an instance of TpfFileDeliveryInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TpfFileDeliveryInfo:
        """Create an instance of TpfFileDeliveryInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TpfFileDeliveryInfo.parse_obj(obj)

        _obj = TpfFileDeliveryInfo.parse_obj({
            "id": obj.get("id"),
            "file_name": obj.get("fileName"),
            "file_hash": obj.get("fileHash"),
            "destination_path": obj.get("destinationPath"),
            "status": obj.get("status"),
            "generated_at": obj.get("generatedAt")
        })
        return _obj

TpfFileDeliveryInfo.update_forward_refs()
