# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class TpfTransactionSearchRequest(BaseModel):
    """
    Request body for the POST transaction-search endpoint. Multiple values in TransactionIds and InstrumentIdentifiers are OR'd within each filter; both filters together are AND'd.  # noqa: E501
    """
    transaction_ids: Optional[List[StrictStr]] = Field(default=None, description="One or more LUSID transaction IDs to search for (max 50). Values are OR'd.", alias="transactionIds")
    instrument_identifiers: Optional[List[StrictStr]] = Field(default=None, description="One or more instrument identifiers in any supported format (ISIN, CUSIP, LUID, etc.) to search for (max 50). Values are OR'd.", alias="instrumentIdentifiers")
    instance_id:  Optional[StrictStr] = Field(None,alias="instanceId", description="Instance ID to filter by. Omit or leave null to search all instances the caller has access to.") 
    var_from: Optional[datetime] = Field(default=None, description="Start of the date range (inclusive). Defaults to 30 days ago if neither From nor To is provided.", alias="from")
    to: Optional[datetime] = Field(default=None, description="End of the date range (inclusive). Defaults to now if not provided.")
    limit: Optional[StrictInt] = Field(default=None, description="Maximum number of results to return per page.")
    page:  Optional[StrictStr] = Field(None,alias="page", description="Pagination token from a previous response NextPage or PreviousPage. Omit for the first page.") 
    status:  Optional[StrictStr] = Field(None,alias="status", description="Publication status to filter by. Valid values: Sent, Skipped, Failed. Optional.") 
    __properties = ["transactionIds", "instrumentIdentifiers", "instanceId", "from", "to", "limit", "page", "status"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TpfTransactionSearchRequest:
        """Create an instance of TpfTransactionSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if transaction_ids (nullable) is None
        # and __fields_set__ contains the field
        if self.transaction_ids is None and "transaction_ids" in self.__fields_set__:
            _dict['transactionIds'] = None

        # set to None if instrument_identifiers (nullable) is None
        # and __fields_set__ contains the field
        if self.instrument_identifiers is None and "instrument_identifiers" in self.__fields_set__:
            _dict['instrumentIdentifiers'] = None

        # set to None if instance_id (nullable) is None
        # and __fields_set__ contains the field
        if self.instance_id is None and "instance_id" in self.__fields_set__:
            _dict['instanceId'] = None

        # set to None if var_from (nullable) is None
        # and __fields_set__ contains the field
        if self.var_from is None and "var_from" in self.__fields_set__:
            _dict['from'] = None

        # set to None if to (nullable) is None
        # and __fields_set__ contains the field
        if self.to is None and "to" in self.__fields_set__:
            _dict['to'] = None

        # set to None if limit (nullable) is None
        # and __fields_set__ contains the field
        if self.limit is None and "limit" in self.__fields_set__:
            _dict['limit'] = None

        # set to None if page (nullable) is None
        # and __fields_set__ contains the field
        if self.page is None and "page" in self.__fields_set__:
            _dict['page'] = None

        # set to None if status (nullable) is None
        # and __fields_set__ contains the field
        if self.status is None and "status" in self.__fields_set__:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TpfTransactionSearchRequest:
        """Create an instance of TpfTransactionSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TpfTransactionSearchRequest.parse_obj(obj)

        _obj = TpfTransactionSearchRequest.parse_obj({
            "transaction_ids": obj.get("transactionIds"),
            "instrument_identifiers": obj.get("instrumentIdentifiers"),
            "instance_id": obj.get("instanceId"),
            "var_from": obj.get("from"),
            "to": obj.get("to"),
            "limit": obj.get("limit"),
            "page": obj.get("page"),
            "status": obj.get("status")
        })
        return _obj

TpfTransactionSearchRequest.update_forward_refs()
