# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from finbourne_horizon.models.destination_response import DestinationResponse

class TransactionResponse(BaseModel):
    """
    Response containing details of a single transaction for a run.  # noqa: E501
    """
    transaction_id:  StrictStr = Field(...,alias="transactionId") 
    publication_status:  StrictStr = Field(...,alias="publicationStatus") 
    portfolio_scope:  Optional[StrictStr] = Field(None,alias="portfolioScope") 
    portfolio_code:  Optional[StrictStr] = Field(None,alias="portfolioCode") 
    instrument_id:  StrictStr = Field(...,alias="instrumentId") 
    instrument_type:  StrictStr = Field(...,alias="instrumentType") 
    instrument_name:  StrictStr = Field(...,alias="instrumentName") 
    trade_date: datetime = Field(alias="tradeDate")
    settlement_date: datetime = Field(alias="settlementDate")
    status:  StrictStr = Field(...,alias="status") 
    skip_reason:  Optional[StrictStr] = Field(None,alias="skipReason") 
    failure_reason:  Optional[StrictStr] = Field(None,alias="failureReason") 
    output_file_name:  Optional[StrictStr] = Field(None,alias="outputFileName") 
    sent_at: Optional[datetime] = Field(default=None, alias="sentAt")
    destinations: List[DestinationResponse]
    __properties = ["transactionId", "publicationStatus", "portfolioScope", "portfolioCode", "instrumentId", "instrumentType", "instrumentName", "tradeDate", "settlementDate", "status", "skipReason", "failureReason", "outputFileName", "sentAt", "destinations"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransactionResponse:
        """Create an instance of TransactionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item in self.destinations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['destinations'] = _items
        # set to None if portfolio_scope (nullable) is None
        # and __fields_set__ contains the field
        if self.portfolio_scope is None and "portfolio_scope" in self.__fields_set__:
            _dict['portfolioScope'] = None

        # set to None if portfolio_code (nullable) is None
        # and __fields_set__ contains the field
        if self.portfolio_code is None and "portfolio_code" in self.__fields_set__:
            _dict['portfolioCode'] = None

        # set to None if skip_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.skip_reason is None and "skip_reason" in self.__fields_set__:
            _dict['skipReason'] = None

        # set to None if failure_reason (nullable) is None
        # and __fields_set__ contains the field
        if self.failure_reason is None and "failure_reason" in self.__fields_set__:
            _dict['failureReason'] = None

        # set to None if output_file_name (nullable) is None
        # and __fields_set__ contains the field
        if self.output_file_name is None and "output_file_name" in self.__fields_set__:
            _dict['outputFileName'] = None

        # set to None if sent_at (nullable) is None
        # and __fields_set__ contains the field
        if self.sent_at is None and "sent_at" in self.__fields_set__:
            _dict['sentAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransactionResponse:
        """Create an instance of TransactionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransactionResponse.parse_obj(obj)

        _obj = TransactionResponse.parse_obj({
            "transaction_id": obj.get("transactionId"),
            "publication_status": obj.get("publicationStatus"),
            "portfolio_scope": obj.get("portfolioScope"),
            "portfolio_code": obj.get("portfolioCode"),
            "instrument_id": obj.get("instrumentId"),
            "instrument_type": obj.get("instrumentType"),
            "instrument_name": obj.get("instrumentName"),
            "trade_date": obj.get("tradeDate"),
            "settlement_date": obj.get("settlementDate"),
            "status": obj.get("status"),
            "skip_reason": obj.get("skipReason"),
            "failure_reason": obj.get("failureReason"),
            "output_file_name": obj.get("outputFileName"),
            "sent_at": obj.get("sentAt"),
            "destinations": [DestinationResponse.from_dict(_item) for _item in obj.get("destinations")] if obj.get("destinations") is not None else None
        })
        return _obj

TransactionResponse.update_forward_refs()
