# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from pydantic.v1 import Field, StrictInt
from typing import List, Optional
from typing_extensions import Annotated
from finbourne_horizon.models.client_configuration_response import ClientConfigurationResponse
from finbourne_horizon.models.create_client_configuration_draft_request import CreateClientConfigurationDraftRequest
from finbourne_horizon.models.update_client_configuration_draft_request import UpdateClientConfigurationDraftRequest

from finbourne_horizon.api_client import ApiClient
from finbourne_horizon.api_response import ApiResponse
from finbourne_horizon.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne_horizon.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class ClientConfigurationsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def create_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], create_client_configuration_draft_request : Annotated[Optional[CreateClientConfigurationDraftRequest], Field(description="Options for the new draft, including optional explicit version and source version.")] = None, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @overload
    def create_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], create_client_configuration_draft_request : Annotated[Optional[CreateClientConfigurationDraftRequest], Field(description="Options for the new draft, including optional explicit version and source version.")] = None, async_req: Optional[bool]=True, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @validate_arguments
    def create_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], create_client_configuration_draft_request : Annotated[Optional[CreateClientConfigurationDraftRequest], Field(description="Options for the new draft, including optional explicit version and source version.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[ClientConfigurationResponse, Awaitable[ClientConfigurationResponse]]:  # noqa: E501
        """[EXPERIMENTAL] CreateClientConfigurationDraft: Create a draft client configuration.  # noqa: E501

        Creates a new draft configuration record. Configurations follow a draft/locked lifecycle: create a draft here, refine it with the update endpoint, then commit it with the lock endpoint. If both majorVersion and minorVersion are omitted in the request body, the next version is assigned automatically by incrementing the minor version of the current highest version (starting at 1.0 if none exists). The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_client_configuration_draft(config_type, name, create_client_configuration_draft_request, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param create_client_configuration_draft_request: Options for the new draft, including optional explicit version and source version.
        :type create_client_configuration_draft_request: CreateClientConfigurationDraftRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ClientConfigurationResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_client_configuration_draft_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.create_client_configuration_draft_with_http_info(config_type, name, create_client_configuration_draft_request, **kwargs)  # noqa: E501

    @validate_arguments
    def create_client_configuration_draft_with_http_info(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], create_client_configuration_draft_request : Annotated[Optional[CreateClientConfigurationDraftRequest], Field(description="Options for the new draft, including optional explicit version and source version.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] CreateClientConfigurationDraft: Create a draft client configuration.  # noqa: E501

        Creates a new draft configuration record. Configurations follow a draft/locked lifecycle: create a draft here, refine it with the update endpoint, then commit it with the lock endpoint. If both majorVersion and minorVersion are omitted in the request body, the next version is assigned automatically by incrementing the minor version of the current highest version (starting at 1.0 if none exists). The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_client_configuration_draft_with_http_info(config_type, name, create_client_configuration_draft_request, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param create_client_configuration_draft_request: Options for the new draft, including optional explicit version and source version.
        :type create_client_configuration_draft_request: CreateClientConfigurationDraftRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ClientConfigurationResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'config_type',
            'name',
            'create_client_configuration_draft_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_client_configuration_draft" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['config_type']:
            _path_params['configType'] = _params['config_type']

        if _params['name']:
            _path_params['name'] = _params['name']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_client_configuration_draft_request'] is not None:
            _body_params = _params['create_client_configuration_draft_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "ClientConfigurationResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
            '409': None,
        }

        return self.api_client.call_api(
            '/api/clientconfiguration/{configType}/{name}/draft', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def get_client_configuration(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[Optional[StrictInt], Field(description="The major version to retrieve. Must be supplied together with minorVersion, or both omitted.")] = None, minor_version : Annotated[Optional[StrictInt], Field(description="The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.")] = None, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @overload
    def get_client_configuration(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[Optional[StrictInt], Field(description="The major version to retrieve. Must be supplied together with minorVersion, or both omitted.")] = None, minor_version : Annotated[Optional[StrictInt], Field(description="The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.")] = None, async_req: Optional[bool]=True, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_client_configuration(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[Optional[StrictInt], Field(description="The major version to retrieve. Must be supplied together with minorVersion, or both omitted.")] = None, minor_version : Annotated[Optional[StrictInt], Field(description="The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[ClientConfigurationResponse, Awaitable[ClientConfigurationResponse]]:  # noqa: E501
        """[EXPERIMENTAL] GetClientConfiguration: Get a client configuration.  # noqa: E501

        Returns a specific configuration record. When both majorVersion and minorVersion are omitted, the highest available version is returned. Both must be supplied together or both omitted. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_client_configuration(config_type, name, major_version, minor_version, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version to retrieve. Must be supplied together with minorVersion, or both omitted.
        :type major_version: int
        :param minor_version: The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.
        :type minor_version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ClientConfigurationResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_client_configuration_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_client_configuration_with_http_info(config_type, name, major_version, minor_version, **kwargs)  # noqa: E501

    @validate_arguments
    def get_client_configuration_with_http_info(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[Optional[StrictInt], Field(description="The major version to retrieve. Must be supplied together with minorVersion, or both omitted.")] = None, minor_version : Annotated[Optional[StrictInt], Field(description="The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] GetClientConfiguration: Get a client configuration.  # noqa: E501

        Returns a specific configuration record. When both majorVersion and minorVersion are omitted, the highest available version is returned. Both must be supplied together or both omitted. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_client_configuration_with_http_info(config_type, name, major_version, minor_version, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version to retrieve. Must be supplied together with minorVersion, or both omitted.
        :type major_version: int
        :param minor_version: The minor version to retrieve. Must be supplied together with majorVersion, or both omitted.
        :type minor_version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ClientConfigurationResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'config_type',
            'name',
            'major_version',
            'minor_version'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_client_configuration" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['config_type']:
            _path_params['configType'] = _params['config_type']

        if _params['name']:
            _path_params['name'] = _params['name']


        # process the query parameters
        _query_params = []
        if _params.get('major_version') is not None:  # noqa: E501
            _query_params.append(('majorVersion', _params['major_version']))

        if _params.get('minor_version') is not None:  # noqa: E501
            _query_params.append(('minorVersion', _params['minor_version']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ClientConfigurationResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/clientconfiguration/{configType}/{name}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_client_configurations(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration to list.")], **kwargs) -> List[ClientConfigurationResponse]:  # noqa: E501
        ...

    @overload
    def list_client_configurations(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration to list.")], async_req: Optional[bool]=True, **kwargs) -> List[ClientConfigurationResponse]:  # noqa: E501
        ...

    @validate_arguments
    def list_client_configurations(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration to list.")], async_req: Optional[bool]=None, **kwargs) -> Union[List[ClientConfigurationResponse], Awaitable[List[ClientConfigurationResponse]]]:  # noqa: E501
        """[EXPERIMENTAL] ListClientConfigurations: List client configurations.  # noqa: E501

        Returns all configuration records for the given config type, across all versions and states (both draft and locked), ordered by version descending. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_client_configurations(config_type, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration to list. (required)
        :type config_type: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[ClientConfigurationResponse]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_client_configurations_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_client_configurations_with_http_info(config_type, **kwargs)  # noqa: E501

    @validate_arguments
    def list_client_configurations_with_http_info(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration to list.")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListClientConfigurations: List client configurations.  # noqa: E501

        Returns all configuration records for the given config type, across all versions and states (both draft and locked), ordered by version descending. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_client_configurations_with_http_info(config_type, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration to list. (required)
        :type config_type: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[ClientConfigurationResponse], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'config_type'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_client_configurations" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['config_type']:
            _path_params['configType'] = _params['config_type']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "List[ClientConfigurationResponse]",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/clientconfiguration/{configType}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def lock_client_configuration_version(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version to lock.")], minor_version : Annotated[StrictInt, Field(description="The minor version to lock.")], **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @overload
    def lock_client_configuration_version(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version to lock.")], minor_version : Annotated[StrictInt, Field(description="The minor version to lock.")], async_req: Optional[bool]=True, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @validate_arguments
    def lock_client_configuration_version(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version to lock.")], minor_version : Annotated[StrictInt, Field(description="The minor version to lock.")], async_req: Optional[bool]=None, **kwargs) -> Union[ClientConfigurationResponse, Awaitable[ClientConfigurationResponse]]:  # noqa: E501
        """[EXPERIMENTAL] LockClientConfigurationVersion: Lock a client configuration version.  # noqa: E501

        Locks a draft configuration version, making it immutable and ready for use. Once locked, a version cannot be edited or unlocked. All versions are retained permanently. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.lock_client_configuration_version(config_type, name, major_version, minor_version, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version to lock. (required)
        :type major_version: int
        :param minor_version: The minor version to lock. (required)
        :type minor_version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ClientConfigurationResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the lock_client_configuration_version_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.lock_client_configuration_version_with_http_info(config_type, name, major_version, minor_version, **kwargs)  # noqa: E501

    @validate_arguments
    def lock_client_configuration_version_with_http_info(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version to lock.")], minor_version : Annotated[StrictInt, Field(description="The minor version to lock.")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] LockClientConfigurationVersion: Lock a client configuration version.  # noqa: E501

        Locks a draft configuration version, making it immutable and ready for use. Once locked, a version cannot be edited or unlocked. All versions are retained permanently. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.lock_client_configuration_version_with_http_info(config_type, name, major_version, minor_version, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version to lock. (required)
        :type major_version: int
        :param minor_version: The minor version to lock. (required)
        :type minor_version: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ClientConfigurationResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'config_type',
            'name',
            'major_version',
            'minor_version'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lock_client_configuration_version" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['config_type']:
            _path_params['configType'] = _params['config_type']

        if _params['name']:
            _path_params['name'] = _params['name']

        if _params['major_version']:
            _path_params['majorVersion'] = _params['major_version']

        if _params['minor_version']:
            _path_params['minorVersion'] = _params['minor_version']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ClientConfigurationResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/clientconfiguration/{configType}/{name}/{majorVersion}/{minorVersion}/lock', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def update_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version of the draft to update.")], minor_version : Annotated[StrictInt, Field(description="The minor version of the draft to update.")], update_client_configuration_draft_request : Annotated[Optional[UpdateClientConfigurationDraftRequest], Field(description="The updated value.")] = None, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @overload
    def update_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version of the draft to update.")], minor_version : Annotated[StrictInt, Field(description="The minor version of the draft to update.")], update_client_configuration_draft_request : Annotated[Optional[UpdateClientConfigurationDraftRequest], Field(description="The updated value.")] = None, async_req: Optional[bool]=True, **kwargs) -> ClientConfigurationResponse:  # noqa: E501
        ...

    @validate_arguments
    def update_client_configuration_draft(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version of the draft to update.")], minor_version : Annotated[StrictInt, Field(description="The minor version of the draft to update.")], update_client_configuration_draft_request : Annotated[Optional[UpdateClientConfigurationDraftRequest], Field(description="The updated value.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[ClientConfigurationResponse, Awaitable[ClientConfigurationResponse]]:  # noqa: E501
        """[EXPERIMENTAL] UpdateClientConfigurationDraft: Update a draft client configuration.  # noqa: E501

        Updates the value of an existing draft configuration. Only draft versions can be updated; locked versions are immutable. This endpoint can be called multiple times before locking. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_client_configuration_draft(config_type, name, major_version, minor_version, update_client_configuration_draft_request, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version of the draft to update. (required)
        :type major_version: int
        :param minor_version: The minor version of the draft to update. (required)
        :type minor_version: int
        :param update_client_configuration_draft_request: The updated value.
        :type update_client_configuration_draft_request: UpdateClientConfigurationDraftRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ClientConfigurationResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_client_configuration_draft_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.update_client_configuration_draft_with_http_info(config_type, name, major_version, minor_version, update_client_configuration_draft_request, **kwargs)  # noqa: E501

    @validate_arguments
    def update_client_configuration_draft_with_http_info(self, config_type : Annotated[StrictStr, Field(..., description="The category of configuration.")], name : Annotated[StrictStr, Field(..., description="The logical name of the configuration.")], major_version : Annotated[StrictInt, Field(description="The major version of the draft to update.")], minor_version : Annotated[StrictInt, Field(description="The minor version of the draft to update.")], update_client_configuration_draft_request : Annotated[Optional[UpdateClientConfigurationDraftRequest], Field(description="The updated value.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] UpdateClientConfigurationDraft: Update a draft client configuration.  # noqa: E501

        Updates the value of an existing draft configuration. Only draft versions can be updated; locked versions are immutable. This endpoint can be called multiple times before locking. The user must be authenticated and entitled to call this method.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_client_configuration_draft_with_http_info(config_type, name, major_version, minor_version, update_client_configuration_draft_request, async_req=True)
        >>> result = thread.get()

        :param config_type: The category of configuration. (required)
        :type config_type: str
        :param name: The logical name of the configuration. (required)
        :type name: str
        :param major_version: The major version of the draft to update. (required)
        :type major_version: int
        :param minor_version: The minor version of the draft to update. (required)
        :type minor_version: int
        :param update_client_configuration_draft_request: The updated value.
        :type update_client_configuration_draft_request: UpdateClientConfigurationDraftRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ClientConfigurationResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'config_type',
            'name',
            'major_version',
            'minor_version',
            'update_client_configuration_draft_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_client_configuration_draft" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['config_type']:
            _path_params['configType'] = _params['config_type']

        if _params['name']:
            _path_params['name'] = _params['name']

        if _params['major_version']:
            _path_params['majorVersion'] = _params['major_version']

        if _params['minor_version']:
            _path_params['minorVersion'] = _params['minor_version']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['update_client_configuration_draft_request'] is not None:
            _body_params = _params['update_client_configuration_draft_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ClientConfigurationResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/clientconfiguration/{configType}/{name}/{majorVersion}/{minorVersion}/draft', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
