# coding: utf-8

"""
    FINBOURNE Horizon API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from pydantic.v1 import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from finbourne_horizon.models.instances_response import InstancesResponse
from finbourne_horizon.models.paged_resource_list_of_instance_run_response import PagedResourceListOfInstanceRunResponse
from finbourne_horizon.models.paged_resource_list_of_run_file_response import PagedResourceListOfRunFileResponse
from finbourne_horizon.models.paged_resource_list_of_tpf_transaction_search_response import PagedResourceListOfTpfTransactionSearchResponse
from finbourne_horizon.models.paged_resource_list_of_transaction_response import PagedResourceListOfTransactionResponse
from finbourne_horizon.models.replay_transactions_request import ReplayTransactionsRequest
from finbourne_horizon.models.replay_transactions_response import ReplayTransactionsResponse
from finbourne_horizon.models.tpf_retry_sftp_response import TpfRetrySftpResponse
from finbourne_horizon.models.transaction_payload_response import TransactionPayloadResponse

from finbourne_horizon.api_client import ApiClient
from finbourne_horizon.api_response import ApiResponse
from finbourne_horizon.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne_horizon.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class TradePublicationFrameworkApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def get_tpf_transaction_history_search(self, transaction_id : Annotated[Optional[StrictStr], Field( description="")] = None, instrument_id : Annotated[Optional[StrictStr], Field( description="")] = None, date_from : Annotated[Optional[StrictStr], Field( description="")] = None, date_to : Annotated[Optional[StrictStr], Field( description="")] = None, status : Annotated[Optional[StrictStr], Field( description="")] = None, instance_id : Annotated[Optional[StrictStr], Field( description="")] = None, page_size : Optional[StrictInt] = None, page_token : Annotated[Optional[StrictStr], Field( description="")] = None, **kwargs) -> PagedResourceListOfTpfTransactionSearchResponse:  # noqa: E501
        ...

    @overload
    def get_tpf_transaction_history_search(self, transaction_id : Annotated[Optional[StrictStr], Field( description="")] = None, instrument_id : Annotated[Optional[StrictStr], Field( description="")] = None, date_from : Annotated[Optional[StrictStr], Field( description="")] = None, date_to : Annotated[Optional[StrictStr], Field( description="")] = None, status : Annotated[Optional[StrictStr], Field( description="")] = None, instance_id : Annotated[Optional[StrictStr], Field( description="")] = None, page_size : Optional[StrictInt] = None, page_token : Annotated[Optional[StrictStr], Field( description="")] = None, async_req: Optional[bool]=True, **kwargs) -> PagedResourceListOfTpfTransactionSearchResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_tpf_transaction_history_search(self, transaction_id : Annotated[Optional[StrictStr], Field( description="")] = None, instrument_id : Annotated[Optional[StrictStr], Field( description="")] = None, date_from : Annotated[Optional[StrictStr], Field( description="")] = None, date_to : Annotated[Optional[StrictStr], Field( description="")] = None, status : Annotated[Optional[StrictStr], Field( description="")] = None, instance_id : Annotated[Optional[StrictStr], Field( description="")] = None, page_size : Optional[StrictInt] = None, page_token : Annotated[Optional[StrictStr], Field( description="")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[PagedResourceListOfTpfTransactionSearchResponse, Awaitable[PagedResourceListOfTpfTransactionSearchResponse]]:  # noqa: E501
        """[EXPERIMENTAL] GetTpfTransactionHistorySearch: Endpoint to search TPF transaction by transaction ID and/or instrument identifier, with filtering by instance and date range  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_tpf_transaction_history_search(transaction_id, instrument_id, date_from, date_to, status, instance_id, page_size, page_token, async_req=True)
        >>> result = thread.get()

        :param transaction_id: 
        :type transaction_id: str
        :param instrument_id: 
        :type instrument_id: str
        :param date_from: 
        :type date_from: str
        :param date_to: 
        :type date_to: str
        :param status: 
        :type status: str
        :param instance_id: 
        :type instance_id: str
        :param page_size: 
        :type page_size: int
        :param page_token: 
        :type page_token: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PagedResourceListOfTpfTransactionSearchResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_tpf_transaction_history_search_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_tpf_transaction_history_search_with_http_info(transaction_id, instrument_id, date_from, date_to, status, instance_id, page_size, page_token, **kwargs)  # noqa: E501

    @validate_arguments
    def get_tpf_transaction_history_search_with_http_info(self, transaction_id : Annotated[Optional[StrictStr], Field( description="")] = None, instrument_id : Annotated[Optional[StrictStr], Field( description="")] = None, date_from : Annotated[Optional[StrictStr], Field( description="")] = None, date_to : Annotated[Optional[StrictStr], Field( description="")] = None, status : Annotated[Optional[StrictStr], Field( description="")] = None, instance_id : Annotated[Optional[StrictStr], Field( description="")] = None, page_size : Optional[StrictInt] = None, page_token : Annotated[Optional[StrictStr], Field( description="")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] GetTpfTransactionHistorySearch: Endpoint to search TPF transaction by transaction ID and/or instrument identifier, with filtering by instance and date range  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_tpf_transaction_history_search_with_http_info(transaction_id, instrument_id, date_from, date_to, status, instance_id, page_size, page_token, async_req=True)
        >>> result = thread.get()

        :param transaction_id: 
        :type transaction_id: str
        :param instrument_id: 
        :type instrument_id: str
        :param date_from: 
        :type date_from: str
        :param date_to: 
        :type date_to: str
        :param status: 
        :type status: str
        :param instance_id: 
        :type instance_id: str
        :param page_size: 
        :type page_size: int
        :param page_token: 
        :type page_token: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PagedResourceListOfTpfTransactionSearchResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'transaction_id',
            'instrument_id',
            'date_from',
            'date_to',
            'status',
            'instance_id',
            'page_size',
            'page_token'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tpf_transaction_history_search" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('transaction_id') is not None:  # noqa: E501
            _query_params.append(('transactionId', _params['transaction_id']))

        if _params.get('instrument_id') is not None:  # noqa: E501
            _query_params.append(('instrumentId', _params['instrument_id']))

        if _params.get('date_from') is not None:  # noqa: E501
            _query_params.append(('dateFrom', _params['date_from']))

        if _params.get('date_to') is not None:  # noqa: E501
            _query_params.append(('dateTo', _params['date_to']))

        if _params.get('status') is not None:  # noqa: E501
            _query_params.append(('status', _params['status']))

        if _params.get('instance_id') is not None:  # noqa: E501
            _query_params.append(('instanceId', _params['instance_id']))

        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        if _params.get('page_token') is not None:  # noqa: E501
            _query_params.append(('pageToken', _params['page_token']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfTpfTransactionSearchResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/transactions/search', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def get_transaction_payload(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], transaction_id : Annotated[StrictStr, Field(...)], **kwargs) -> TransactionPayloadResponse:  # noqa: E501
        ...

    @overload
    def get_transaction_payload(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], transaction_id : Annotated[StrictStr, Field(...)], async_req: Optional[bool]=True, **kwargs) -> TransactionPayloadResponse:  # noqa: E501
        ...

    @validate_arguments
    def get_transaction_payload(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], transaction_id : Annotated[StrictStr, Field(...)], async_req: Optional[bool]=None, **kwargs) -> Union[TransactionPayloadResponse, Awaitable[TransactionPayloadResponse]]:  # noqa: E501
        """[EXPERIMENTAL] GetTransactionPayload: Transaction payload detail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_transaction_payload(instance_id, run_id, transaction_id, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param transaction_id: (required)
        :type transaction_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TransactionPayloadResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_transaction_payload_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_transaction_payload_with_http_info(instance_id, run_id, transaction_id, **kwargs)  # noqa: E501

    @validate_arguments
    def get_transaction_payload_with_http_info(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], transaction_id : Annotated[StrictStr, Field(...)], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] GetTransactionPayload: Transaction payload detail  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_transaction_payload_with_http_info(instance_id, run_id, transaction_id, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param transaction_id: (required)
        :type transaction_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TransactionPayloadResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'run_id',
            'transaction_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_transaction_payload" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']

        if _params['run_id']:
            _path_params['runId'] = _params['run_id']

        if _params['transaction_id']:
            _path_params['transactionId'] = _params['transaction_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "TransactionPayloadResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/runs/{runId}/transactions/{transactionId}/payload', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_instance_run_history(self, instance_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> PagedResourceListOfInstanceRunResponse:  # noqa: E501
        ...

    @overload
    def list_instance_run_history(self, instance_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=True, **kwargs) -> PagedResourceListOfInstanceRunResponse:  # noqa: E501
        ...

    @validate_arguments
    def list_instance_run_history(self, instance_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=None, **kwargs) -> Union[PagedResourceListOfInstanceRunResponse, Awaitable[PagedResourceListOfInstanceRunResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ListInstanceRunHistory: List run history for a given TPF instance, with pagination support.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_instance_run_history(instance_id, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PagedResourceListOfInstanceRunResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_instance_run_history_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_instance_run_history_with_http_info(instance_id, page, page_size, **kwargs)  # noqa: E501

    @validate_arguments
    def list_instance_run_history_with_http_info(self, instance_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListInstanceRunHistory: List run history for a given TPF instance, with pagination support.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_instance_run_history_with_http_info(instance_id, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PagedResourceListOfInstanceRunResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'page',
            'page_size'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_instance_run_history" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']


        # process the query parameters
        _query_params = []
        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfInstanceRunResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/runs', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_instances_with_status(self, **kwargs) -> InstancesResponse:  # noqa: E501
        ...

    @overload
    def list_instances_with_status(self, async_req: Optional[bool]=True, **kwargs) -> InstancesResponse:  # noqa: E501
        ...

    @validate_arguments
    def list_instances_with_status(self, async_req: Optional[bool]=None, **kwargs) -> Union[InstancesResponse, Awaitable[InstancesResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ListInstancesWithStatus: Lists all instances of the Trade Publication Framework (TPF).  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_instances_with_status(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InstancesResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_instances_with_status_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_instances_with_status_with_http_info(**kwargs)  # noqa: E501

    @validate_arguments
    def list_instances_with_status_with_http_info(self, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListInstancesWithStatus: Lists all instances of the Trade Publication Framework (TPF).  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_instances_with_status_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InstancesResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_instances_with_status" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "InstancesResponse",
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_run_files(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> PagedResourceListOfRunFileResponse:  # noqa: E501
        ...

    @overload
    def list_run_files(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=True, **kwargs) -> PagedResourceListOfRunFileResponse:  # noqa: E501
        ...

    @validate_arguments
    def list_run_files(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=None, **kwargs) -> Union[PagedResourceListOfRunFileResponse, Awaitable[PagedResourceListOfRunFileResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ListRunFiles: List Files in a run  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_run_files(instance_id, run_id, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PagedResourceListOfRunFileResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_run_files_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_run_files_with_http_info(instance_id, run_id, page, page_size, **kwargs)  # noqa: E501

    @validate_arguments
    def list_run_files_with_http_info(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListRunFiles: List Files in a run  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_run_files_with_http_info(instance_id, run_id, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PagedResourceListOfRunFileResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'run_id',
            'page',
            'page_size'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_run_files" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']

        if _params['run_id']:
            _path_params['runId'] = _params['run_id']


        # process the query parameters
        _query_params = []
        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfRunFileResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/runs/{runId}/files', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def list_run_transactions(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], status : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> PagedResourceListOfTransactionResponse:  # noqa: E501
        ...

    @overload
    def list_run_transactions(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], status : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=True, **kwargs) -> PagedResourceListOfTransactionResponse:  # noqa: E501
        ...

    @validate_arguments
    def list_run_transactions(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], status : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, async_req: Optional[bool]=None, **kwargs) -> Union[PagedResourceListOfTransactionResponse, Awaitable[PagedResourceListOfTransactionResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ListRunTransactions: List Transactions in a run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_run_transactions(instance_id, run_id, status, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param status: (required)
        :type status: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PagedResourceListOfTransactionResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_run_transactions_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.list_run_transactions_with_http_info(instance_id, run_id, status, page, page_size, **kwargs)  # noqa: E501

    @validate_arguments
    def list_run_transactions_with_http_info(self, instance_id : Annotated[StrictStr, Field(...)], run_id : Annotated[StrictStr, Field(...)], status : Annotated[StrictStr, Field(...)], page : Annotated[Optional[StrictStr], Field()] = None, page_size : Optional[StrictInt] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ListRunTransactions: List Transactions in a run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_run_transactions_with_http_info(instance_id, run_id, status, page, page_size, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param run_id: (required)
        :type run_id: str
        :param status: (required)
        :type status: str
        :param page:
        :type page: str
        :param page_size:
        :type page_size: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PagedResourceListOfTransactionResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'run_id',
            'status',
            'page',
            'page_size'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_run_transactions" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']

        if _params['run_id']:
            _path_params['runId'] = _params['run_id']


        # process the query parameters
        _query_params = []
        if _params.get('status') is not None:  # noqa: E501
            _query_params.append(('status', _params['status']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('page_size') is not None:  # noqa: E501
            _query_params.append(('pageSize', _params['page_size']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfTransactionResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/runs/{runId}/transactions', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def replay_transactions(self, instance_id : Annotated[StrictStr, Field(...)], replay_transactions_request : ReplayTransactionsRequest, **kwargs) -> ReplayTransactionsResponse:  # noqa: E501
        ...

    @overload
    def replay_transactions(self, instance_id : Annotated[StrictStr, Field(...)], replay_transactions_request : ReplayTransactionsRequest, async_req: Optional[bool]=True, **kwargs) -> ReplayTransactionsResponse:  # noqa: E501
        ...

    @validate_arguments
    def replay_transactions(self, instance_id : Annotated[StrictStr, Field(...)], replay_transactions_request : ReplayTransactionsRequest, async_req: Optional[bool]=None, **kwargs) -> Union[ReplayTransactionsResponse, Awaitable[ReplayTransactionsResponse]]:  # noqa: E501
        """[EXPERIMENTAL] ReplayTransactions: Replay one or more transactions through a TPF instance  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.replay_transactions(instance_id, replay_transactions_request, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param replay_transactions_request: (required)
        :type replay_transactions_request: ReplayTransactionsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: ReplayTransactionsResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the replay_transactions_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.replay_transactions_with_http_info(instance_id, replay_transactions_request, **kwargs)  # noqa: E501

    @validate_arguments
    def replay_transactions_with_http_info(self, instance_id : Annotated[StrictStr, Field(...)], replay_transactions_request : ReplayTransactionsRequest, **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] ReplayTransactions: Replay one or more transactions through a TPF instance  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.replay_transactions_with_http_info(instance_id, replay_transactions_request, async_req=True)
        >>> result = thread.get()

        :param instance_id: (required)
        :type instance_id: str
        :param replay_transactions_request: (required)
        :type replay_transactions_request: ReplayTransactionsRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(ReplayTransactionsResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'replay_transactions_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method replay_transactions" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['replay_transactions_request'] is not None:
            _body_params = _params['replay_transactions_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ReplayTransactionsResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/replay', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def retry_tpf_sftp_delivery(self, instance_id : Annotated[StrictStr, Field(..., description="Integration instance ID")], file_id : Annotated[StrictInt, Field(description="File delivery ID to retry")], **kwargs) -> TpfRetrySftpResponse:  # noqa: E501
        ...

    @overload
    def retry_tpf_sftp_delivery(self, instance_id : Annotated[StrictStr, Field(..., description="Integration instance ID")], file_id : Annotated[StrictInt, Field(description="File delivery ID to retry")], async_req: Optional[bool]=True, **kwargs) -> TpfRetrySftpResponse:  # noqa: E501
        ...

    @validate_arguments
    def retry_tpf_sftp_delivery(self, instance_id : Annotated[StrictStr, Field(..., description="Integration instance ID")], file_id : Annotated[StrictInt, Field(description="File delivery ID to retry")], async_req: Optional[bool]=None, **kwargs) -> Union[TpfRetrySftpResponse, Awaitable[TpfRetrySftpResponse]]:  # noqa: E501
        """[EXPERIMENTAL] RetryTpfSftpDelivery: Retry SFTP delivery for a previously sent TPF file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retry_tpf_sftp_delivery(instance_id, file_id, async_req=True)
        >>> result = thread.get()

        :param instance_id: Integration instance ID (required)
        :type instance_id: str
        :param file_id: File delivery ID to retry (required)
        :type file_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TpfRetrySftpResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the retry_tpf_sftp_delivery_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.retry_tpf_sftp_delivery_with_http_info(instance_id, file_id, **kwargs)  # noqa: E501

    @validate_arguments
    def retry_tpf_sftp_delivery_with_http_info(self, instance_id : Annotated[StrictStr, Field(..., description="Integration instance ID")], file_id : Annotated[StrictInt, Field(description="File delivery ID to retry")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EXPERIMENTAL] RetryTpfSftpDelivery: Retry SFTP delivery for a previously sent TPF file  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retry_tpf_sftp_delivery_with_http_info(instance_id, file_id, async_req=True)
        >>> result = thread.get()

        :param instance_id: Integration instance ID (required)
        :type instance_id: str
        :param file_id: File delivery ID to retry (required)
        :type file_id: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TpfRetrySftpResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'instance_id',
            'file_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retry_tpf_sftp_delivery" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['instance_id']:
            _path_params['instanceId'] = _params['instance_id']

        if _params['file_id']:
            _path_params['fileId'] = _params['file_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "TpfRetrySftpResponse",
            '400': "LusidValidationProblemDetails",
            '404': None,
            '409': None,
        }

        return self.api_client.call_api(
            '/api/trade-publication-framework/instances/{instanceId}/files/{fileId}/retry-sftp', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
